meta_title: "48hrs - Be one of the locals!"
meta_description: "This is your platform for getting in touch with the locals through personal stories and experiences."
meta_image: "city.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@TimThuis" # indispensable pour les Twitter Cards
